CREATE TABLE IF NOT EXISTS times(
	id BIGSERIAL PRIMARY KEY,
	name VARCHAR(45) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS jogadores(
	id BIGSERIAL PRIMARY KEY,
	name VARCHAR(45) NOT NULL,
	age INTEGER,
	time_id INTEGER NOT NULL,
	FOREIGN KEY (time_id) REFERENCES times(id)
);

